Agrochrono/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls'))
]

weather/urls.py
from django.urls import path
from . import views

app_name = 'agrochrono'

urlpatterns = [
    path('', views.index, name='index'),
    path('cotacoes/', views.CotacoesView.as_view(), name='cotacoes'),
    path('maps/', views.maps, name='maps'),
    path('save_location/', views.save_location, name='save_location'),
    path('delete_location/<int:location_id>/', views.delete_location, name='delete_location'),
    path('register/', views.register, name='registrar'),
    path('login/', views.user_login, name='login'),
    path('noticias/', views.NoticiasView.as_view(), name='noticias')
]

weather/models.py
from django.db import models
from django.contrib.auth.models import User

class WeatherData(models.Model):
    temperature = models.DecimalField(max_digits=5, decimal_places=2)
    clouds = models.DecimalField(max_digits=5, decimal_places=2)
    humidity = models.DecimalField(max_digits=5, decimal_places=2)
    wind_speed = models.DecimalField(max_digits=5, decimal_places=2)
    pressure = models.DecimalField(max_digits=5, decimal_places=2)

class SavedLocation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, default="Localização Desconhecida")
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return self.name

weather/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("Este endereço de e-mail já está em uso.")
        return email

class LoginForm(forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

weather/views.py
import requests
import geocoder
import json
from django.views import generic
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponse
from .models import SavedLocation
from django.contrib.auth import authenticate, login as auth_login
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from .forms import UserRegistrationForm, LoginForm
from django.template.loader import render_to_string

def get_current_location_coordinates():
    g = geocoder.ip('me')
    if g.latlng is not None:
        return g.latlng
    else:
        return None

def get_current_weather_hgbrasil(lat, lon):
    url = f'https://api.hgbrasil.com/weather?key=426ebee6&lat={lat}&lon={lon}&fields=temp,date,time,condition_code,description,currently,humidity,cloudiness,rain,wind_speedy,wind_direction,wind_cardinal,moon_phase,condition_slug,city_name,timezone'
    response = requests.get(url)
    
    if response.status_code == 200:
        data = response.json().get('results', {})
        
        moon_phase_mapping = {
            "new": "Nova",
            "waxing_crescent": "Crescente",
            "first_quarter": "Quarto Crescente",
            "waxing_gibbous": "Crescente Gibosa",
            "full": "Cheia",
            "waning_gibbous": "Minguante Gibosa",
            "last_quarter": "Quarto Minguante",
            "waning_crescent": "Minguante"
        }
        
        weather_info = {
            'temperature': data.get('temp', 'N/A'),
            'date': data.get('date', 'N/A'),
            'time': data.get('time', 'N/A'),
            'description': data.get('description', 'N/A'),
            'humidity': data.get('humidity', 'N/A'),
            'cloudiness': data.get('cloudiness', 'N/A'),
            'rain': data.get('rain', 'N/A'),
            'wind_speedy': data.get('wind_speedy', 'N/A'),
            'wind_direction': data.get('wind_direction', 'N/A'),
            'wind_cardinal': data.get('wind_cardinal', 'N/A'),
            'moon_phase': moon_phase_mapping.get(data.get('moon_phase', ''), data.get('moon_phase', 'N/A')),
            'city_name': data.get('city', 'N/A')
        }
        
        return weather_info
    else:
        print("Erro ao acessar a API hgbrasil:", response.status_code)
        return None

def five_days_prevision(lat, lon):
    url = f'https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&units=metric&lang=pt_br&appid=af561dcbdd69011cb3d872ad2dffcbe7'
    response = requests.get(url)
    prevision_data = []
    if response.status_code == 200:
        data = response.json()
        for forecast in data['list']:
            dt_txt = forecast['dt_txt']
            temp = forecast['main']['temp']
            description = forecast['weather'][0]['description']
            humidity = forecast['main']['humidity']
            precipitation = round(forecast['pop'] * 100, 1)
            rain_3hours = forecast.get('rain', {}).get('3h', 0)
            snow_3hours = forecast.get('snow', {}).get('3h', 0)

            date, time = dt_txt.split(' ')
            formatted_date = "/".join(reversed(date.split('-')))
            formatted_time = time[:5]

            prevision_data.append({
                "date": formatted_date,
                "time": formatted_time,
                "temperature": temp,
                "humidity": humidity,
                "description": description,
                "precipitation": precipitation,
                "rain": rain_3hours,
                "snow": snow_3hours
            })
    else:
        print("Erro ao acessar a API:", response.status_code)
    return prevision_data

def maps(request):
    coordinates = get_current_location_coordinates()
    return render(request, 'maps/maps.html', {'coordinates': coordinates})

@csrf_exempt
@login_required
def save_location(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        lat = data.get('lat')
        lon = data.get('lon')
        name = data.get('name')

        if lat is not None and lon is not None and name:
            SavedLocation.objects.create(user=request.user, latitude=lat, longitude=lon, name=name)
            return JsonResponse({'status': 'success'})
        else:
            return JsonResponse({'status': 'error'}, status=400)
    return JsonResponse({'status': 'error'}, status=405)

@csrf_exempt
@login_required
def delete_location(request, location_id):
    location = get_object_or_404(SavedLocation, pk=location_id)
    location.delete()
    return JsonResponse({'message': 'Localização excluída com sucesso.'})

def weather_alerts(lat, lon):
    api_key = 'ec66f849b3ad4d7f860171005242005'
    base_url = 'http://api.weatherapi.com/v1'
    endpoint = '/forecast.json'

    location = f'{lat}, {lon}'

    params = {
        'key': api_key,
        'q': location,
        'alerts': 'yes',
        'lang': 'pt'
    }
    response = requests.get(base_url + endpoint, params=params)
    if response.status_code == 200:
        data = response.json()
        alerts_data = data.get('alerts', {}).get('alert', []) 
        
        formatted_alerts = []
        for alert_data in alerts_data:
            formatted_alert = {
                'headline': alert_data.get('headline', ''),
                'msgType': alert_data.get('msgtype', ''),
                'severity': alert_data.get('severity', ''),
                'urgency': alert_data.get('urgency', ''),
                'areas': alert_data.get('areas', ''),
                'category': alert_data.get('category', ''),
                'certainty': alert_data.get('certainty', ''),
                'event': alert_data.get('event', ''),
                'note': alert_data.get('note', ''),
                'effective': alert_data.get('effective', ''),
                'expires': alert_data.get('expires', ''),
                'desc': alert_data.get('desc', ''),
                'instruction': alert_data.get('instruction', '')
            }
            formatted_alerts.append(formatted_alert)
        return formatted_alerts
    else:
        print("Erro ao acessar a API:", response.status_code)
        return []

def extract_information(desc):
    keywords = ['WHAT', 'WHERE', 'WHEN', 'IMPACTS']
    extracted_info = []

    for keyword in keywords:
        index = desc.find(keyword)
        if index != -1:
            next_keyword_index = desc.find('*', index + len(keyword))
            if next_keyword_index != -1:
                extracted_info.append(desc[index:next_keyword_index])
            else:
                extracted_info.append(desc[index:])

    return extracted_info

def index(request):
    lat = request.GET.get('lat')
    lon = request.GET.get('lon')
    if lat and lon:
        lat = lat.replace(',', '.')
        lon = lon.replace(',', '.')
        lat = float(lat)
        lon = float(lon)
    else:
        coordinates = get_current_location_coordinates()
        if coordinates:
            lat, lon = coordinates
        else:
            lat, lon = None, None

    weather_info = None
    prevision = None
    alerts = None
    available_dates = []
    selected_date = request.GET.get('date', None)
    saved_locations = []

    if request.user.is_authenticated:
        saved_locations = SavedLocation.objects.filter(user=request.user)

    selected_location = request.GET.get('location_id')
    if selected_location == "current_location":
        lat, lon = get_current_location_coordinates()
        if lat is None or lon is None:
            error_message = "Não foi possível obter a localização atual. Por favor, tente novamente mais tarde."

    elif selected_location:
        location = SavedLocation.objects.get(id=selected_location)
        lat, lon = location.latitude, location.longitude    

    if lat and lon:
        weather_info = get_current_weather_hgbrasil(lat, lon)
        prevision = five_days_prevision(lat, lon)
        alerts = weather_alerts(lat, lon)

        for forecast in prevision:
            date_str = forecast["date"]
            if date_str not in available_dates:
                available_dates.append(date_str)

        if selected_date:
            selected_prevision = [forecast for forecast in prevision if forecast["date"].startswith(selected_date)]
            prevision = selected_prevision

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        print(prevision, selected_date)
        html = render_to_string('previsao_parcial.html', {
            'prevision': prevision,
            'selected_date': selected_date
        })
        return HttpResponse(html)

    if alerts:
        for alert in alerts:
            desc = alert['desc']
            extracted_info = extract_information(desc)
            alert['extracted_info'] = '\n'.join(extracted_info)

    return render(request, 'index.html', {
        'weather_info': weather_info,
        'prevision': prevision,
        'alerts': alerts,
        'available_dates': available_dates,
        'selected_date': selected_date,
        'saved_locations': saved_locations,
        'lat': lat,
        'lon': lon
    })


class CotacoesView(generic.TemplateView):
    template_name = 'cotacoes/cotacoes.html'

class NoticiasView(generic.TemplateView):
    template_name = 'noticias/noticias.html'

@csrf_exempt
def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('/')
    else:
        form = UserRegistrationForm()
    return render(request, 'user/register.html', {'form': form})

@csrf_exempt
def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

weather/templates/user/login.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">

    <title>Login</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'user/loginstyle.css' %}">
</head>
<body>
    <div id="cabecalho"><h1>Agrochrono</h1></div>
    <form method="post">
        <h1><strong>Login</strong></h1>
        {% csrf_token %}
        <div id="campos">
            <div id="campo_username">
                <label for="id_username">Usuário:</label>
                {{ form.username }}
            </div>
            <br>

            <div id="campo_password">
                <label for="id_senha">Senha:</label>
                {{ form.password }}
            </div>
            <br>
            {% if erro %}
            <p>{{ erro }}</p>
            {% endif %}
            <button id='submit_button' type="submit">Login</button>
        </div>
    </form>
    <div id='registrar'>
        <h3>Ainda não está cadastrado?</h3>
        <br>
        <a href="{% url 'agrochrono:registrar' %}">Clique aqui!</a>
    </div>
</body>
</html>

weather/templates/user/register.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">

    <title>Registrar</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'user/registerstyle.css' %}">
</head>
<body>
    <div id="cabecalho"><h1>Agrochrono</h1></div>
    <form method="post">
        {% csrf_token %}
        <div id="containers">
            <h1><strong>Cadastro de usuário</strong></h1>
            <div id="campos">
                <div id="campo_username">
                    <label for="id_username">Usuário:</label>
                    {{ form.username }}
                </div>
                <br>

                <div id="campo_email">
                    <label for="id_email">Email:</label>
                    {{ form.email }}
                </div>
                <br>

                <div id="campo_password">
                    <label for="id_password1">Senha:</label>
                    {{ form.password1 }}
                </div>
                <br>

                <div id="campo_password2">
                    <label for="id_password2">Confirmação de senha:</label>
                    {{ form.password2 }}
                </div>
                <br>

                {% if form.errors %}
                <div class="errors">
                    <p>Ocorreu um problema:</p>
                    <ul>
                        {% for field_errors in form.errors.values %}
                            {% for error in field_errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}

                <button id='submit_button' type="submit">Confirmar</button>
            </div>
        </div>
    </form>
    <div id='login'>
        <h3>Já está cadastrado?</h3>
        <br>
        <a href="{% url 'agrochrono:login' %}">Clique aqui!</a>
    </div>
</body>
</html>