Agrochrono/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls'))
]

weather/urls.py
from django.urls import path
from . import views

app_name = 'agrochrono'

urlpatterns = [
    path('', views.index, name='index'),
    path('cotacoes/', views.CotacoesView.as_view(), name='cotacoes'),
    path('maps/', views.maps, name='maps'),
    path('save_location/', views.save_location, name='save_location'),
    path('delete_location/<int:location_id>/', views.delete_location, name='delete_location'),
    path('register/', views.register, name='registrar'),
    path('login/', views.user_login, name='login'),
    path('noticias/', views.NoticiasView.as_view(), name='noticias')
]

weather/models.py
from django.db import models
from django.contrib.auth.models import User

class WeatherData(models.Model):
    temperature = models.DecimalField(max_digits=5, decimal_places=2)
    clouds = models.DecimalField(max_digits=5, decimal_places=2)
    humidity = models.DecimalField(max_digits=5, decimal_places=2)
    wind_speed = models.DecimalField(max_digits=5, decimal_places=2)
    pressure = models.DecimalField(max_digits=5, decimal_places=2)

class SavedLocation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, default="Localização Desconhecida")
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return self.name

weather/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("Este endereço de e-mail já está em uso.")
        return email

class LoginForm(forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

weather/views.py
import requests
import geocoder
import json
from django.views import generic
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponse
from .models import SavedLocation
from django.contrib.auth import authenticate, login as auth_login
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from .forms import UserRegistrationForm, LoginForm
from django.template.loader import render_to_string

def get_current_location_coordinates():
    g = geocoder.ip('me')
    if g.latlng is not None:
        return g.latlng
    else:
        return None

def get_current_weather_hgbrasil(lat, lon):
    url = f'https://api.hgbrasil.com/weather?key=426ebee6&lat={lat}&lon={lon}&fields=temp,date,time,condition_code,description,currently,humidity,cloudiness,rain,wind_speedy,wind_direction,wind_cardinal,moon_phase,condition_slug,city_name,timezone'
    response = requests.get(url)
    
    if response.status_code == 200:
        data = response.json().get('results', {})
        
        moon_phase_mapping = {
            "new": "Nova",
            "waxing_crescent": "Crescente",
            "first_quarter": "Quarto Crescente",
            "waxing_gibbous": "Crescente Gibosa",
            "full": "Cheia",
            "waning_gibbous": "Minguante Gibosa",
            "last_quarter": "Quarto Minguante",
            "waning_crescent": "Minguante"
        }
        
        weather_info = {
            'temperature': data.get('temp', 'N/A'),
            'date': data.get('date', 'N/A'),
            'time': data.get('time', 'N/A'),
            'description': data.get('description', 'N/A'),
            'humidity': data.get('humidity', 'N/A'),
            'cloudiness': data.get('cloudiness', 'N/A'),
            'rain': data.get('rain', 'N/A'),
            'wind_speedy': data.get('wind_speedy', 'N/A'),
            'wind_direction': data.get('wind_direction', 'N/A'),
            'wind_cardinal': data.get('wind_cardinal', 'N/A'),
            'moon_phase': moon_phase_mapping.get(data.get('moon_phase', ''), data.get('moon_phase', 'N/A')),
            'city_name': data.get('city', 'N/A')
        }
        
        return weather_info
    else:
        print("Erro ao acessar a API hgbrasil:", response.status_code)
        return None

def five_days_prevision(lat, lon):
    url = f'https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&units=metric&lang=pt_br&appid=af561dcbdd69011cb3d872ad2dffcbe7'
    response = requests.get(url)
    prevision_data = []
    if response.status_code == 200:
        data = response.json()
        for forecast in data['list']:
            dt_txt = forecast['dt_txt']
            temp = forecast['main']['temp']
            description = forecast['weather'][0]['description']
            humidity = forecast['main']['humidity']
            precipitation = round(forecast['pop'] * 100, 1)
            rain_3hours = forecast.get('rain', {}).get('3h', 0)
            snow_3hours = forecast.get('snow', {}).get('3h', 0)

            date, time = dt_txt.split(' ')
            formatted_date = "/".join(reversed(date.split('-')))
            formatted_time = time[:5]

            prevision_data.append({
                "date": formatted_date,
                "time": formatted_time,
                "temperature": temp,
                "humidity": humidity,
                "description": description,
                "precipitation": precipitation,
                "rain": rain_3hours,
                "snow": snow_3hours
            })
    else:
        print("Erro ao acessar a API:", response.status_code)
    return prevision_data

def maps(request):
    coordinates = get_current_location_coordinates()
    return render(request, 'maps/maps.html', {'coordinates': coordinates})

@csrf_exempt
@login_required
def save_location(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        lat = data.get('lat')
        lon = data.get('lon')
        name = data.get('name')

        if lat is not None and lon is not None and name:
            SavedLocation.objects.create(user=request.user, latitude=lat, longitude=lon, name=name)
            return JsonResponse({'status': 'success'})
        else:
            return JsonResponse({'status': 'error'}, status=400)
    return JsonResponse({'status': 'error'}, status=405)

@csrf_exempt
@login_required
def delete_location(request, location_id):
    location = get_object_or_404(SavedLocation, pk=location_id)
    location.delete()
    return JsonResponse({'message': 'Localização excluída com sucesso.'})

def weather_alerts(lat, lon):
    api_key = 'ec66f849b3ad4d7f860171005242005'
    base_url = 'http://api.weatherapi.com/v1'
    endpoint = '/forecast.json'

    location = f'{lat}, {lon}'

    params = {
        'key': api_key,
        'q': location,
        'alerts': 'yes',
        'lang': 'pt'
    }
    response = requests.get(base_url + endpoint, params=params)
    if response.status_code == 200:
        data = response.json()
        alerts_data = data.get('alerts', {}).get('alert', []) 
        
        formatted_alerts = []
        for alert_data in alerts_data:
            formatted_alert = {
                'headline': alert_data.get('headline', ''),
                'msgType': alert_data.get('msgtype', ''),
                'severity': alert_data.get('severity', ''),
                'urgency': alert_data.get('urgency', ''),
                'areas': alert_data.get('areas', ''),
                'category': alert_data.get('category', ''),
                'certainty': alert_data.get('certainty', ''),
                'event': alert_data.get('event', ''),
                'note': alert_data.get('note', ''),
                'effective': alert_data.get('effective', ''),
                'expires': alert_data.get('expires', ''),
                'desc': alert_data.get('desc', ''),
                'instruction': alert_data.get('instruction', '')
            }
            formatted_alerts.append(formatted_alert)
        return formatted_alerts
    else:
        print("Erro ao acessar a API:", response.status_code)
        return []

def extract_information(desc):
    keywords = ['WHAT', 'WHERE', 'WHEN', 'IMPACTS']
    extracted_info = []

    for keyword in keywords:
        index = desc.find(keyword)
        if index != -1:
            next_keyword_index = desc.find('*', index + len(keyword))
            if next_keyword_index != -1:
                extracted_info.append(desc[index:next_keyword_index])
            else:
                extracted_info.append(desc[index:])

    return extracted_info

def index(request):
    lat = request.GET.get('lat')
    lon = request.GET.get('lon')
    if lat and lon:
        lat = lat.replace(',', '.')
        lon = lon.replace(',', '.')
        lat = float(lat)
        lon = float(lon)
    else:
        coordinates = get_current_location_coordinates()
        if coordinates:
            lat, lon = coordinates
        else:
            lat, lon = None, None

    weather_info = None
    prevision = None
    alerts = None
    available_dates = []
    selected_date = request.GET.get('date', None)
    saved_locations = []

    if request.user.is_authenticated:
        saved_locations = SavedLocation.objects.filter(user=request.user)

    selected_location = request.GET.get('location_id')
    if selected_location == "current_location":
        lat, lon = get_current_location_coordinates()
        if lat is None or lon is None:
            error_message = "Não foi possível obter a localização atual. Por favor, tente novamente mais tarde."

    elif selected_location:
        location = SavedLocation.objects.get(id=selected_location)
        lat, lon = location.latitude, location.longitude    

    if lat and lon:
        weather_info = get_current_weather_hgbrasil(lat, lon)
        prevision = five_days_prevision(lat, lon)
        alerts = weather_alerts(lat, lon)

        for forecast in prevision:
            date_str = forecast["date"]
            if date_str not in available_dates:
                available_dates.append(date_str)

        if selected_date:
            selected_prevision = [forecast for forecast in prevision if forecast["date"].startswith(selected_date)]
            prevision = selected_prevision

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        print(prevision, selected_date)
        html = render_to_string('previsao_parcial.html', {
            'prevision': prevision,
            'selected_date': selected_date
        })
        return HttpResponse(html)

    if alerts:
        for alert in alerts:
            desc = alert['desc']
            extracted_info = extract_information(desc)
            alert['extracted_info'] = '\n'.join(extracted_info)

    return render(request, 'index.html', {
        'weather_info': weather_info,
        'prevision': prevision,
        'alerts': alerts,
        'available_dates': available_dates,
        'selected_date': selected_date,
        'saved_locations': saved_locations,
        'lat': lat,
        'lon': lon
    })


class CotacoesView(generic.TemplateView):
    template_name = 'cotacoes/cotacoes.html'

class NoticiasView(generic.TemplateView):
    template_name = 'noticias/noticias.html'

@csrf_exempt
def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('/')
    else:
        form = UserRegistrationForm()
    return render(request, 'user/register.html', {'form': form})

@csrf_exempt
def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

weather/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">

    <title>Agrochrono</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'indexstyle.css' %}">
</head>
<body>
    <div id="cabecalho"><h1>Agrochrono</h1></div>
    <div id="containers">
        <h3 id="selectedLocationName"></h3>
        {% if request.user.is_authenticated %}
        <div id="current_location">
            <label for="savedLocations">Localizações salvas:</label>
            <select id="savedLocations">
                <option value="current_location" data-lat="{{ lat }}" data-lon="{{ lon }}">Localização atual</option>
                {% for location in saved_locations %}
                    <option value="{{ location.id }}" data-lat="{{ location.latitude }}" data-lon="{{ location.longitude }}">{{ location.name }}</option>
                {% endfor %}
            </select>
            <br>
            <button id="selectLocation">Selecionar</button>
            <button id="delete-location">Excluir</button>
            {% if error_message %}
                <div class="error-message">
                    <p>{{ error_message }}</p>
                </div>
            {% endif %}
        {% else %}
            <div id="autenticar">
                <div id="login">
                    <p><strong>Faça login para acessar suas localizações salvas.</strong></p>
                    <ion-icon name="arrow-redo"></ion-icon><a href="{% url 'agrochrono:login' %}">Login</a>
                </div>
                <div id="registrar">
                    <p><strong>Ou registre-se para salvar localizações.</strong></p>
                    <ion-icon name="arrow-redo"></ion-icon><a href="{% url 'agrochrono:registrar' %}">Registrar</a>
                </div>
            </div>
        {% endif %}
        </div>
        <div id="weathers">
            <div id="current_weather_container">
                {% if weather_info %}
                <h2>Condições climáticas atuais</h2>
                <div id="current_weather_infos">
                    <p> <strong>Temperatura:</strong> {{ weather_info.temperature }} ºC</p>
                    <p> <strong>Última atualização:</strong> {{ weather_info.time }}</p>
                    <p> <strong>Descrição:</strong> {{ weather_info.description }}</p>
                    <p> <strong>Umidade:</strong> {{ weather_info.humidity }}%</p>
                    <p> <strong>Nebulosidade:</strong> {{ weather_info.cloudiness }}%</p>
                    <p> <strong>Chuva:</strong> {{ weather_info.rain }} mm</p>
                    <p> <strong>Velocidade do Vento:</strong> {{ weather_info.wind_speedy }}</p>
                    <p> <strong>Direção do Vento:</strong> {{ weather_info.wind_direction }}° ({{ weather_info.wind_cardinal }})</p>
                    <p> <strong>Fase da Lua:</strong> {{ weather_info.moon_phase }}</p>
                    {% else %}
                    <p>Não foi possível obter os dados atuais.</p>
                    {% endif %}
                </div>
            </div>
            <div id="forecast_weather">
                {% if prevision %}
                <h2>Previsão para 5 dias</h2>
                <form id="dateForm" action="{% url 'agrochrono:index' %}">
                    <label for="dateSelector">Selecionar data:</label>
                    <select name="date" id="dateSelector">
                        <option value="" {% if not selected_date %}selected{% endif %}>--/--/----</option>
                        {% for date in available_dates %}
                            <option value="{{ date }}" {% if date == selected_date %}selected{% endif %}>{{ date }}</option>
                        {% endfor %}
                    </select>
                    <input type="hidden" id="latInput" name="lat" value="{{ lat }}">
                    <input type="hidden" id="lonInput" name="lon" value="{{ lon }}">
                </form>
                <div id="forecastContainer">
                    {% include 'previsao_parcial.html' %}
                </div>
                {% else %}
                    <p>Não foi possível obter a previsão.</p>
                {% endif %}
            </div>
            <div id="links">
                <a href="{% url 'agrochrono:noticias' %}"><h3>Notícias</h3></a>
                <a href="{% url 'agrochrono:cotacoes'%}"><h3>Cotações agricolas</h3></a>
                <a href="{% url 'agrochrono:maps' %}"><h3>Mapas climatológicos</h3></a>
            </div>
        </div>
        <h2>Alertas climáticos</h2>
        <div id="alerts">
            {% if alerts %}
            {% for alert in alerts %}
            <div id="alert_box">
                <strong>{{ alert.headline }}</strong><br>
                <p> - Evento: {{ alert.event }}</p>
                <p> - Ínicio: {{ alert.effective }}</p>
                <p> - Previsão de termíno: {{ alert.expires }}  </p>
                <p> - Informações adicionais: {{ alert.extracted_info|linebreaks }}</p>
            </div>
            {% endfor %}
            {% else %}
            <p>Nenhum alerta disponível.</p>
            {% endif %}
        </div>
    </div>
    <script>
        document.getElementById('dateSelector').addEventListener('change', function() {
            document.getElementById('dateForm').submit();
        });
    
        document.addEventListener('DOMContentLoaded', function() {
            const savedLocationsElement = document.getElementById('savedLocations');
            const selectLocationButton = document.getElementById('selectLocation');
            const deleteLocationButton = document.getElementById('delete-location');
            const selectedLocationNameElement = document.getElementById('selectedLocationName');
    
            const selectedLocationId = localStorage.getItem('selectedLocationId');
            if (selectedLocationId) {
                savedLocationsElement.value = selectedLocationId;
            }
    
            const selectedLocationName = localStorage.getItem('selectedLocationName');
            if (selectedLocationName) {
                selectedLocationNameElement.textContent = selectedLocationName;
            }
    
            if (selectLocationButton) {
                selectLocationButton.addEventListener('click', function() {
                    const selectedLocationId = savedLocationsElement.value;
                    if (selectedLocationId) {
                        const selectedLocation = savedLocationsElement.options[savedLocationsElement.selectedIndex];
                        const lat = selectedLocation.dataset.lat;
                        const lon = selectedLocation.dataset.lon;

                        localStorage.setItem('selectedLocationId', selectedLocationId);
                        localStorage.setItem('selectedLocationName', selectedLocation.text);
    
                        window.location.href = `/?location_id=${selectedLocationId}&lat=${lat}&lon=${lon}`;
                    } else {
                        alert("Selecione uma localização.");
                    }
                });
            }
    
            if (deleteLocationButton) {
                deleteLocationButton.addEventListener('click', function() {
                    const selectedLocationId = savedLocationsElement.value;
                    if (selectedLocationId) {
                        if (confirm("Tem certeza de que deseja excluir esta localização?")) {
                            fetch(`/delete_location/${selectedLocationId}/`, {
                                method: 'POST',
                                headers: {
                                    'Content-Type': 'application/json',
                                    'X-CSRFToken': '{{ csrf_token }}'
                                }
                            }).then(response => {
                                if (response.ok) {
                                    savedLocationsElement.removeChild(savedLocationsElement.options[savedLocationsElement.selectedIndex]);
                                    savedLocationsElement.value = '';
                                    
                                    localStorage.removeItem('selectedLocationId');
                                    localStorage.removeItem('selectedLocationName');
    
                                    selectedLocationNameElement.textContent = '';
                                    alert("Localização excluída com sucesso.");
                                } else {
                                    alert("Erro ao excluir a localização.");
                                }
                            });
                        }
                    } else {
                        alert("Selecione uma localização para excluir.");
                    }
                });
            }
        });
    </script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</body>
</html>

weather/templates/previsao_parcial.html
<div id="forecastContainer">
    {% if selected_date %}
        <div class="forecast-list">
            {% for forecast in prevision %}
                <div class="forecast-item">
                    <dl>
                        <dt>Data:</dt>
                        <dd>{{ forecast.date }}</dd>
                        <dt>Horário:</dt>
                        <dd>{{ forecast.time }}</dd>
                        <dt>Temperatura:</dt>
                        <dd>{{ forecast.temperature }} ºC</dd>
                        <dt>Tempo:</dt>
                        <dd>{{ forecast.description }}</dd>
                        <dt>Umidade:</dt>
                        <dd>{{ forecast.humidity }}%</dd>
                        <dt>Precipitação:</dt>
                        <dd>{{ forecast.precipitation }}%</dd>
                        <dt>Volume de chuva (últimas 3 horas):</dt>
                        <dd>{{ forecast.rain }} mm</dd>
                        <dt>Volume de neve (últimas 3 horas):</dt>
                        <dd>{{ forecast.snow }} mm</dd>
                    </dl>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>Selecione uma data para ver a previsão.</p>
    {% endif %}
</div>